### ISSUE TITLE
xworkspaces segfault

### ISSUE THREAD

**Issue by jonhoo** [polybar/polybar#1033]
This segfault is pretty rare, and I'm not entirely sure what triggers it. Managed to catch it with gdb by running polybar under the debugger all day until it crashed:

```
Thread 13 "polybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcbfff700 (LWP 1106)]
polybar::v3_1_0_56_gbd022c9_git::builder::node (this=0x555555a5c8d0,
    label=<error reading variable: Cannot access memory at address 0x7361625f70614d67>, add_space=false)
    at /home/jon/dev/others/polybar/src/components/builder.cpp:244
244       if (label->m_padding.right > 0) {
(gdb) bt
#0  polybar::v3_1_0_56_gbd022c9_git::builder::node (this=0x555555a5c8d0,
    label=<error reading variable: Cannot access memory at address 0x7361625f70614d67>, add_space=false)
    at /home/jon/dev/others/polybar/src/components/builder.cpp:244
#1  0x00005555557227ce in polybar::v3_1_0_56_gbd022c9_git::modules::xworkspaces_module::build (this=0x555555a5c490,
    builder=0x555555a5c8d0, tag=...) at /home/jon/dev/others/polybar/src/modules/xworkspaces.cpp:300
#2  0x000055555572b7b9 in polybar::v3_1_0_56_gbd022c9_git::modules::module<polybar::v3_1_0_56_gbd022c9_git::modules::xworkspaces_module>::get_output[abi:cxx11]() (this=0x555555a5c490)
    at /home/jon/dev/others/polybar/include/modules/meta/base.inl:159
#3  0x00005555557222bd in polybar::v3_1_0_56_gbd022c9_git::modules::xworkspaces_module::get_output[abi:cxx11]() (
    this=0x555555a5c490) at /home/jon/dev/others/polybar/src/modules/xworkspaces.cpp:264
#4  0x000055555572b1d0 in polybar::v3_1_0_56_gbd022c9_git::modules::module<polybar::v3_1_0_56_gbd022c9_git::modules::xworkspaces_module>::contents[abi:cxx11]() (this=0x555555a5c490)
    at /home/jon/dev/others/polybar/include/modules/meta/base.inl:81
#5  0x000055555567cc76 in polybar::v3_1_0_56_gbd022c9_git::controller::process_update (this=<optimized out>,
    force=false) at /home/jon/dev/others/polybar/src/components/controller.cpp:465
#6  0x0000555555679c1a in polybar::v3_1_0_56_gbd022c9_git::controller::process_eventqueue (this=0x555555a54500)
    at /home/jon/dev/others/polybar/src/components/controller.cpp:357
#7  0x00007ffff5985b9f in std::execute_native_thread_routine (__p=0x555555a5df90)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#8  0x00007ffff515208c in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff4e89e7f in clone () from /usr/lib/libc.so.6
```

**Comment by jonhoo** [comment]
This is running with my (relatively minor) patch from #972, encapsulated by bd022c95c2014d8b7fd09ebf695a401d0929a7bf. I don't think that's related to the crash.

**Comment by jonhoo** [comment]
If it's relevant, [this](https://github.com/jonhoo/configs/blob/e49453b7e9c4c3525a6d032e11cab0d127ba9a13/polybar/config) is my config, and I'm using `xmonad`.

**Comment by jonhoo** [comment]
The issue *seems* to be correlated with running HexChat, which also crashes when polybar does.

**Comment by NBonaparte** [comment]
What is the output of `xprop -root`?

Does it just crash randomly or only when HexChat is also running?

**Comment by jonhoo** [comment]
```console
$ xprop -root
AT_SPI_BUS(STRING) = "unix:abstract=/tmp/dbus-oRARjUBAMc,guid=b5e1f2a8c05971d3dc0570455a8704cb"
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0xa00004
_XROOTPMAP_ID(PIXMAP): pixmap id # 0xa00004
GDK_VISUALS(INTEGER) = 299, 342
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 4, 105, -79, 36, 1, 1, 1, 1, 25, 24, 1, 4, -91, 55, 35, 120, 58, 61, 21, -93, 84, 77, -96, 39, 18, 80, 84, -65, -17, 0, 113, 79, -127, -128, -127, 64, -107, 0, -87, 64, -77, 0, -47, -64, 1, 1, 40, 60, -128, -96, 112, -80, 35, 64, 48, 32, 54, 0, 34, 96, 33, 0, 0, 26, 0, 0, 0, -3, 0, 50, 76, 30, 83, 17, 0, 10, 32, 32, 32, 32, 32, 32, 0, 0, 0, -4, 0, 80, 65, 50, 52, 56, 10, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, -1, 0, 69, 54, 76, 77, 81, 83, 48, 55, 53, 56, 54, 51, 10, 1, -83, 2, 3, 24, -15, 75, -112, 5, 4, 3, 2, 1, 17, 18, 19, 20, 31, 35, 9, 7, 7, -125, 1, 0, 0, 26, 54, -128, -96, 112, 56, 30, 64, 48, 32, 53, 0, 34, 96, 33, 0, 0, 26, 102, 33, 86, -86, 81, 0, 30, 48, 70, -113, 51, 0, 34, 96, 33, 0, 0, 30, 1, 29, 0, 114, 81, -48, 30, 32, 110, 40, 85, 0, 34, 96, 33, 0, 0, 30, -116, 10, -48, -118, 32, -32, 45, 16, 16, 62, -106, 0, 34, 96, 33, 0, 0, 24, 1, 29, -128, 24, 113, 28, 22, 32, 88, 44, 37, 0, 34, 96, 33, 0, 0, -98, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x200001
_NET_SUPPORTED(ATOM) = _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_STATE_HIDDEN, _NET_NUMBER_OF_DESKTOPS, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_ACTIVE_WINDOW, _NET_WM_DESKTOP, _NET_WM_STRUT
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x2600003
_NET_CURRENT_DESKTOP(CARDINAL) = 3
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x1800011, 0xc00003, 0x2400003, 0x2600003, 0x600003, 0x2800001
_NET_CLIENT_LIST(WINDOW): window id # 0x1800011, 0xc00003, 0x2400003, 0x2600003, 0x600003, 0x2800001
_NET_DESKTOP_NAMES(UTF8_STRING) = "web", "code", "a", "b", "c", "mx", "sfx"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 7
RESOURCE_MANAGER(STRING) = "*.foreground:\t#D8DEE9\n*.background:\t#2E3440\n*.cursorColor:\t#D8DEE9\n*fading:\t35\n*fadeColor:\t#4C566A\n*.color0:\t#3B4252\n*.color1:\t#BF616A\n*.color2:\t#A3BE8C\n*.color3:\t#EBCB8B\n*.color4:\t#81A1C1\n*.color5:\t#B48EAD\n*.color6:\t#88C0D0\n*.color7:\t#E5E9F0\n*.color8:\t#4C566A\n*.color9:\t#BF616A\n*.color10:\t#A3BE8C\n*.color11:\t#EBCB8B\n*.color12:\t#81A1C1\n*.color13:\t#B48EAD\n*.color14:\t#8FBCBB\n*.color15:\t#ECEFF4\nemacs*geometry:\t120x50\n*faceName:\txft:SourceCodePro:size=10\n*font:\txft:SourceCodePro:size=10\n*multiClickTime:\t300\n*international:\ttrue\nXcursor.theme:\tdefault\nXcursor.size:\t16 ! 32, 48 or 64 may also be good values\nURxvt.depth:\t32\nURxvt.secondaryScroll:\tfalse\nURxvt*saveLines:\t12000\nURxvt*scrollTtyOutput:\tfalse\nURxvt*scrollWithBuffer:\ttrue\nURxvt*scrollTtyKeypress:\ttrue\nURxvt.scrollBar:\tfalse\nURxvt.geometry:\t130x30\nURxvt.urlLauncher:\t/usr/bin/firefox\nURxvt.url-launcher:\t/usr/bin/firefox\nURxvt.matcher.button:\t1\nURxvt.keysym.Control-Up:\t\\033[1;5A\nURxvt.keysym.Control-Down:\t\\033[1;5B\nURxvt.keysym.Control-Left:\t\\033[1;5D\nURxvt.keysym.Control-Right:\t\\033[1;5C\nURxvt.keysym.M-z:\t\302\257\\\\_(\343\203\204)_/\302\257\nURxvt.perl-ext-common:\tdefault,clipboard\nURxvt.keysym.M-c:\teval:selection_to_clipboard\nURxvt.keysym.M-v:\teval:paste_clipboard\nXft.dpi:\t96\nXft.lcdfilter:\tlcddefault\nXft.antialias:\ttrue\nXft.autohint:\tfalse\nXft.hinting:\ttrue\nXft.hintstyle:\thintfull\nXft.rgba:\trgb\nxterm*geometry:\t100x25\nxterm*dynamicColors:\ttrue\nxterm*utf8:\t1\nxterm*eightBitInput:\ttrue\nxterm*saveLines:\t12000\nxterm*scrollTtyKeypress:\ttrue\nxterm*scrollTtyOutput:\tfalse\nxterm*jumpScroll:\ttrue\nxterm*multiScroll:\ttrue\nxterm*toolBar:\tfalse\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 1
Xorg_Seat(STRING) = "seat0"
```

I don't know if the crashes only occur with HexChat running. I don't *think* that's the case, but the crashes are so rare that it's been a few days since last time (and I don't remember if HexChat was running that time). I'll update the next time I see a crash.

**Comment by jonhoo** [comment]
`polybar` just crashed without HexChat running. I unfortunately wasn't running it under gdb, so don't have a backtrace for you.

**Comment by jonhoo** [comment]
For what it's worth, this *seems* to trigger when a system bar status icon changes.

**Comment by jonhoo** [comment]
Just segfaulted again in a slightly different place with 4f6e37449b4c2b66d81c2457501166efbcbb4d95 + #972:
```
Thread 13 "polybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcbfff700 (LWP 11111)]
polybar::v3_1_0_65_g3fe5c40_git::modules::xworkspaces_module::build (this=0x555555a5e4a0, builder=0x555555a5e8e0,
    tag=...) at /home/jon/dev/others/polybar/src/modules/xworkspaces.cpp:293
293           for (auto&& desktop : m_viewports[m_index]->desktops) {
(gdb) bt
#0  polybar::v3_1_0_65_g3fe5c40_git::modules::xworkspaces_module::build (this=0x555555a5e4a0, builder=0x555555a5e8e0,
    tag=...) at /home/jon/dev/others/polybar/src/modules/xworkspaces.cpp:293
#1  0x000055555572d199 in polybar::v3_1_0_65_g3fe5c40_git::modules::module<polybar::v3_1_0_65_g3fe5c40_git::modules::xworkspaces_module>::get_output[abi:cxx11]() (this=0x555555a5e4a0)
    at /home/jon/dev/others/polybar/include/modules/meta/base.inl:159
#2  0x0000555555723c9d in polybar::v3_1_0_65_g3fe5c40_git::modules::xworkspaces_module::get_output[abi:cxx11]() (
    this=0x555555a5e4a0) at /home/jon/dev/others/polybar/src/modules/xworkspaces.cpp:264
#3  0x000055555572cbb0 in polybar::v3_1_0_65_g3fe5c40_git::modules::module<polybar::v3_1_0_65_g3fe5c40_git::modules::xworkspaces_module>::contents[abi:cxx11]() (this=0x555555a5e4a0)
    at /home/jon/dev/others/polybar/include/modules/meta/base.inl:81
#4  0x000055555567cc96 in polybar::v3_1_0_65_g3fe5c40_git::controller::process_update (this=<optimized out>,
    force=false) at /home/jon/dev/others/polybar/src/components/controller.cpp:478
#5  0x0000555555679caa in polybar::v3_1_0_65_g3fe5c40_git::controller::process_eventqueue (this=0x555555a56500)
    at /home/jon/dev/others/polybar/src/components/controller.cpp:370
#6  0x00007ffff5985b9f in std::execute_native_thread_routine (__p=0x555555a58090)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#7  0x00007ffff515208c in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007ffff4e89e7f in clone () from /usr/lib/libc.so.6
```

**Comment by NBonaparte** [comment]
I have a feeling this might be X event-related, but I'm not absolutely sure.

This might be a stretch, but it might be helpful to monitor what X events are occurring right before the segfault.

**Comment by jonhoo** [comment]
How would I do that?

**Comment by NBonaparte** [comment]
You could insert some logging into `xworkspaces_module::handle()` to print which property changed and possibly add a timestamp to determine when it occurred.

https://github.com/jaagr/polybar/blob/692e6d9b4a2e023804353dee430b865dfedccd78/src/modules/xworkspaces.cpp#L97-L113

**Comment by jamesbvaughan** [comment]
I'm also getting infrequent segfaults and I'm running xmonad and the xworkspaces module. I haven't been able to identify what triggers them but I'll post in here if I do.

**Comment by jamesbvaughan** [comment]
I'm also getting infrequent segfaults and I'm running xmonad and the xworkspaces module. I haven't been able to identify what triggers them but I'll post in here if I do.

**Comment by kronn** [comment]
@jonhoo suggested that I might be getting this segfault as well. If I can determine the trigger or propose a fix, I will report back here.

I hope that "Given enough eyeballs, all bugs are shallow" holds in this case. :-)

**Comment by NBonaparte** [comment]
I think this might be caused by multiple X events occurring in succession causing race conditions, which can be solved by locking in the handler.

**Comment by fdietze** [comment]
When ewmh/xworkspaces is enabled, polybar also crashes multiple times in a session for me. I'm on NixOs 18.03, using xmonad.

It happend so often, that I disabled the xworkspaces module, but still not very predictably. It seems like it has to do something with fullscreen or floating windows.

**Comment by fdietze** [comment]
This could be related: https://www.reddit.com/r/xmonad/comments/72yodp/psa_do_not_use_both_ewmh_and_the_event_hook/

**Comment by jonhoo** [comment]
@fdietze hmm.. I do not have any of those duplicated, yet I still see the segfauly. Not multiple times a session though, so that does perhaps suggest that it is indeed about events racing.

**Comment by willprice** [comment]
I believe I'm also running into this. I can replicate the issue quite easily when running VLC and toggling through lots of videos which causes the window title to update. I've built polybar in debug mode and replicated the issue

```
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./polybar...done.
(gdb) run
Starting program: /home/will/src/polybar/src/polybar/build/bin/polybar bar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1c23700 (LWP 20050)]
[New Thread 0x7fffed422700 (LWP 20051)]
[New Thread 0x7fffecc21700 (LWP 20052)]
[Thread 0x7fffecc21700 (LWP 20052) exited]
[New Thread 0x7fffdbfff700 (LWP 20053)]
[New Thread 0x7fffdb7fe700 (LWP 20054)]
[Thread 0x7fffdbfff700 (LWP 20053) exited]
[New Thread 0x7fffdaffd700 (LWP 20055)]
[New Thread 0x7fffda7fc700 (LWP 20056)]
[New Thread 0x7fffd9ffb700 (LWP 20057)]
[New Thread 0x7fffd97fa700 (LWP 20058)]
[New Thread 0x7fffd8ff9700 (LWP 20059)]
[New Thread 0x7fffc7fff700 (LWP 20060)]
[New Thread 0x7fffc77fe700 (LWP 20061)]
[New Thread 0x7fffc6ffd700 (LWP 20062)]
[New Thread 0x7fffc67fc700 (LWP 20063)]
[New Thread 0x7fffc5ffb700 (LWP 20064)]
[New Thread 0x7fffc57fa700 (LWP 20065)]
[New Thread 0x7fffc4ff9700 (LWP 20066)]
[New Thread 0x7fffb3fff700 (LWP 20067)]
[Thread 0x7fffc4ff9700 (LWP 20066) exited]
[New Thread 0x7fffb2c46700 (LWP 20068)]
[Thread 0x7fffb2c46700 (LWP 20068) exited]

Thread 19 "polybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb3fff700 (LWP 20067)]
0x00005555558e77d0 in std::__shared_ptr<polybar::v3_2_1::drawtypes::label, (__gnu_cxx::_Lock_policy)2>::get (this=0x12500000010)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:1286
1286          { return _M_ptr; }
(gdb) bt full
#0  0x00005555558e77d0 in std::__shared_ptr<polybar::v3_2_1::drawtypes::label, (__gnu_cxx::_Lock_policy)2>::get (this=0x12500000010)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:1286
No locals.
#1  0x0000555555a09cd6 in polybar::v3_2_1::modules::xworkspaces_module::build (this=0x555555ba8630, builder=0x555555ba8a70, tag="<label-state>")
    at /home/will/src/polybar/src/polybar/src/modules/xworkspaces.cpp:294
        desktop = std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555c00530}
        __for_range = std::vector of length 9, capacity 16 = {std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555bfe050}, 
          std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555bfbea0}, std::unique_ptr<polybar::v3_2_1::modules::desktop> = {
            get() = 0x555555c095a0}, std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555c03270}, 
          std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555c004a0}, std::unique_ptr<polybar::v3_2_1::modules::desktop> = {
            get() = 0x555555bfd040}, std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555bfd070}, 
          std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555c00530}, std::unique_ptr<polybar::v3_2_1::modules::desktop> = {
            get() = 0x555555baa980}}
        __for_begin = std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x555555c00530}
        __for_end = std::unique_ptr<polybar::v3_2_1::modules::desktop> = {get() = 0x0}
        added_states = 7
#2  0x0000555555a0bdcc in polybar::v3_2_1::modules::module<polybar::v3_2_1::modules::xworkspaces_module>::get_output[abi:cxx11]() (
    this=0x555555ba8630) at /home/will/src/polybar/src/polybar/include/modules/meta/base.inl:160
        tag = "<label-state>"
        guard = {_M_device = @0x555555ba8840}
        format_name = "format"
        format = std::shared_ptr<polybar::v3_2_1::modules::module_format> (use count 2, weak count 0) = {get() = 0x555555baca80}
        no_tag_built = true
        fake_no_tag_built = false
        tag_built = false
        mingap = 1
        start = 0
        end = 12
        value = "<label-state>"
#3  0x0000555555a096a9 in polybar::v3_2_1::modules::xworkspaces_module::get_output[abi:cxx11]() (this=0x555555ba8630)
    at /home/will/src/polybar/src/polybar/src/modules/xworkspaces.cpp:264
        output = ""
#4  0x0000555555a0b58b in polybar::v3_2_1::modules::module<polybar::v3_2_1::modules::xworkspaces_module>::contents[abi:cxx11]() (
    this=0x555555ba8630) at /home/will/src/polybar/src/polybar/include/modules/meta/base.inl:82
No locals.
#5  0x00005555558fe396 in polybar::v3_2_1::controller::process_update (this=0x555555baa460, force=false)
    at /home/will/src/polybar/src/polybar/src/components/controller.cpp:481
        module_contents = ""
        module = std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8630}
        __for_range = std::vector of length 1, capacity 1 = {std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8630}}
        __for_begin = std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8630}
        __for_end = std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x0}
        block_contents = ""
        is_left = true
        is_center = false
        is_right = false
        is_first = true
        block = @0x555555bab6d0: {first = polybar::v3_2_1::alignment::LEFT, second = std::vector of length 1, capacity 1 = {
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8630}}}
        __for_range = std::map with 3 elements = {[polybar::v3_2_1::alignment::LEFT] = std::vector of length 1, capacity 1 = {
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8630}}, 
--Type <RET> for more, q to quit, c to continue without paging--
          [polybar::v3_2_1::alignment::CENTER] = std::vector of length 1, capacity 1 = {
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555bb67e0}}, 
          [polybar::v3_2_1::alignment::RIGHT] = std::vector of length 11, capacity 16 = {
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555babdb0}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555bfc870}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555bfd880}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555bfe860}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555b84400}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c015b0}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c02980}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c04e30}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c07300}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c08a60}, 
            std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c09b60}}}
        __for_begin = 
      {first = polybar::v3_2_1::alignment::LEFT, second = std::vector of length 1, capacity 1 = {std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8630}}}
        __for_end = 
      {first = polybar::v3_2_1::alignment::RIGHT, second = std::vector of length 4, capacity 4 = {std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555ba8970}, std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555bac0e0}, std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c08d98}, std::unique_ptr<polybar::v3_2_1::modules::module_interface> = {get() = 0x555555c09e90}}}
        bar = @0x7fffb3ffe8e0: {window = 104857602, monitor = std::shared_ptr<polybar::v3_2_1::randr_output> (use count 32, weak count 0) = {
            get() = 0x555555ba7d80}, origin = polybar::v3_2_1::edge::TOP, size = {w = 2560, h = 24}, pos = {x = 0, y = 293}, offset = {x = 0,
            y = 0}, center = {x = 1280, y = 12}, padding = {left = 0, right = 0}, margin = {left = 0, right = 0}, module_margin = {left = 1,
            right = 1}, strut = {left = 0, right = 0, top = 0, bottom = 0}, background = 4280427042, foreground = 4292861919,
          background_steps = std::vector of length 0, capacity 0, underline = {color = 4294901760, size = 3}, overline = {color = 4294901760,
            size = 3}, borders = std::unordered_map with 4 elements = {[polybar::v3_2_1::edge::RIGHT] = {color = 0, size = 0},
            [polybar::v3_2_1::edge::LEFT] = {color = 0, size = 0}, [polybar::v3_2_1::edge::TOP] = {color = 0, size = 0},
            [polybar::v3_2_1::edge::BOTTOM] = {color = 0, size = 0}}, radius = {top = 0, bottom = 0}, spacing = 0, separator = "",
          wmname = "polybar-bar_DP2-2-8", locale = "", override_redirect = false, cursor = "", cursor_click = "pointer",
          cursor_scroll = "ns-resize", actions = std::vector of length 0, capacity 0, dimmed = false, dimvalue = 1, shaded = false, shade_size = {
            w = 1, h = 1}, shade_pos = {x = 1, y = 1}}
        contents = ""
        separator = ""
        padding_left = ""
        padding_right = ""
        margin_left = " "
        margin_right = " "
#6  0x00005555558fd786 in polybar::v3_2_1::controller::process_eventqueue (this=0x555555baa460)
    at /home/will/src/polybar/src/polybar/src/components/controller.cpp:394
        next = {type = 1, flag = false}
        swallowed = 6
        evt = {type = 1, flag = false}
#7  0x0000555555908790 in std::__invoke_impl<void, void (polybar::v3_2_1::controller::*)(), polybar::v3_2_1::controller*> (
    __f=@0x555555c0d360: (void (polybar::v3_2_1::controller::*)(polybar::v3_2_1::controller * const)) 0x5555558fd41e <polybar::v3_2_1::controller::process_eventqueue()>, __t=@0x555555c0d358: 0x555555baa460) at /usr/include/c++/8.2.1/bits/invoke.h:73
No locals.
#8  0x00005555559043f0 in std::__invoke<void (polybar::v3_2_1::controller::*)(), polybar::v3_2_1::controller*> (
    __fn=@0x555555c0d360: (void (polybar::v3_2_1::controller::*)(polybar::v3_2_1::controller * const)) 0x5555558fd41e <polybar::v3_2_1::controller::process_eventqueue()>, __args#0=@0x555555c0d358: 0x555555baa460) at /usr/include/c++/8.2.1/bits/invoke.h:95
--Type <RET> for more, q to quit, c to continue without paging--
No locals.
#9  0x000055555591660f in std::thread::_Invoker<std::tuple<void (polybar::v3_2_1::controller::*)(), polybar::v3_2_1::controller*> >::_M_invoke<0ul, 1ul> (this=0x555555c0d358) at /usr/include/c++/8.2.1/thread:244
No locals.
#10 0x00005555559165b5 in std::thread::_Invoker<std::tuple<void (polybar::v3_2_1::controller::*)(), polybar::v3_2_1::controller*> >::operator() (
    this=0x555555c0d358) at /usr/include/c++/8.2.1/thread:253
No locals.
#11 0x00005555559164ca in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (polybar::v3_2_1::controller::*)(), polybar::v3_2_1::controller*> > >::_M_run (this=0x555555c0d350) at /usr/include/c++/8.2.1/thread:196
No locals.
#12 0x00007ffff69b7063 in std::execute_native_thread_routine (__p=0x555555c0d350) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = 0x555555c0d350}
#13 0x00007ffff6740a9d in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#14 0x00007ffff6670b23 in clone () from /usr/lib/libc.so.6
No symbol table info available.
```

I've got a corefile as well should that be useful for debugging

The relevant part of my polybar config

```
[module/workspaces]
type= internal/xworkspaces
enable-click = false
enable-scroll = false
;
; icon-[0-9]+ = <desktop-name>;<icon>
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktops using:
; $ xprop -root _NET_DESKTOP_NAMES
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-9 = 9;
icon-default = 

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(active|urgent|occupied|empty)>
; Default: <label-state>
format = <label-state>

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-active = " %index% %icon% " 
label-active-foreground = #3f3f3f
label-active-background = #ffffff 
label-active-underline = #fba922

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-occupied = %icon%
label-occupied-background = #3f3f3f
label-occupied-underline = #ffffff

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-underline = #9b0a20

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-empty = " %index% %icon% "
label-empty-foreground = #999
label-empty-background = #3f3f3f

```

Polybar commit: a5bdce981150e244a6fab37b3bc22ccc1182e9b1
```

**Comment by kronn** [comment]
I think I solved this in #882 / #1444 (well, I committed what others hinted me at). 

@willprice @jonhoo Could give that version a try and see if it works for you as well?

**Comment by jonhoo** [comment]
I actually haven't seen this segfault for a while! It still happens *very* occasionally, but I haven't been able to actively reproduce it like before. @kronn is #882 in a place where you think it can be used as the standard polybar build now?

**Comment by willprice** [comment]
@kronn, I've tested your fork and can confirm I've not had any issues. I'll try the latest master version on this repo to and see if I can reproduce the segfaults. 
Thanks @kronn and @jonhoo for the help.

**Comment by willprice** [comment]
Hi @jonhoo,
I can still reproduce this on commit 6ca4f0678506276d1ccc508296bf174901126ab2 by cycling through videos very quickly on vlc (hitting 'n' and 'p') and toggling through windows.

```
$ gdb --args ./polybar bar
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./polybar...done.
(gdb) run
Starting program: /home/will/src/polybar/src/polybar/build/bin/polybar bar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1c23700 (LWP 20149)]
warn: Monitor "DP2-2-8" not found, reverting to fallback "eDP1"
[New Thread 0x7fffed422700 (LWP 20150)]
[New Thread 0x7fffecc21700 (LWP 20151)]
[Thread 0x7fffecc21700 (LWP 20151) exited]
[New Thread 0x7fffdbfff700 (LWP 20152)]
[New Thread 0x7fffdb7fe700 (LWP 20153)]
[Thread 0x7fffdbfff700 (LWP 20152) exited]
[New Thread 0x7fffdaffd700 (LWP 20154)]
[New Thread 0x7fffda7fc700 (LWP 20155)]
[New Thread 0x7fffd9ffb700 (LWP 20156)]
[New Thread 0x7fffd97fa700 (LWP 20157)]
[New Thread 0x7fffd8ff9700 (LWP 20158)]
[New Thread 0x7fffbffff700 (LWP 20159)]
[New Thread 0x7fffbf7fe700 (LWP 20160)]
[New Thread 0x7fffbeffd700 (LWP 20161)]
[New Thread 0x7fffbe7fc700 (LWP 20162)]
[New Thread 0x7fffbdffb700 (LWP 20163)]
[New Thread 0x7fffbd7fa700 (LWP 20164)]
[New Thread 0x7fffbcff9700 (LWP 20165)]
[New Thread 0x7fffaffff700 (LWP 20166)]
[Thread 0x7fffbcff9700 (LWP 20165) exited]
[New Thread 0x7fffaec46700 (LWP 20167)]
[Thread 0x7fffaec46700 (LWP 20167) exited]

Thread 19 "polybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffaffff700 (LWP 20166)]
0x0000555555925f14 in std::__shared_ptr<polybar::v3_2_0_60_g6ca4f067::drawtypes::label, (__gnu_cxx::_Lock_policy)2>::get (
    this=0x10) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:1286
1286          { return _M_ptr; }
(gdb) backtrace
#0  0x0000555555925f14 in std::__shared_ptr<polybar::v3_2_0_60_g6ca4f067::drawtypes::label, (__gnu_cxx::_Lock_policy)2>::get (
    this=0x10) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:1286
#1  0x0000555555a48d24 in polybar::v3_2_0_60_g6ca4f067::modules::xworkspaces_module::build (this=0x555555bf0480, 
    builder=0x555555bee5c0, tag="<label-state>") at /home/will/src/polybar/src/polybar/src/modules/xworkspaces.cpp:294
#2  0x0000555555a4ae1a in polybar::v3_2_0_60_g6ca4f067::modules::module<polybar::v3_2_0_60_g6ca4f067::modules::xworkspaces_module>::get_output[abi:cxx11]() (this=0x555555bf0480) at /home/will/src/polybar/src/polybar/include/modules/meta/base.inl:160
#3  0x0000555555a486f7 in polybar::v3_2_0_60_g6ca4f067::modules::xworkspaces_module::get_output[abi:cxx11]() (this=0x555555bf0480)
    at /home/will/src/polybar/src/polybar/src/modules/xworkspaces.cpp:264
#4  0x0000555555a4a5d9 in polybar::v3_2_0_60_g6ca4f067::modules::module<polybar::v3_2_0_60_g6ca4f067::modules::xworkspaces_module>::contents[abi:cxx11]() (this=0x555555bf0480) at /home/will/src/polybar/src/polybar/include/modules/meta/base.inl:82
#5  0x000055555593cb08 in polybar::v3_2_0_60_g6ca4f067::controller::process_update (this=0x555555bca7f0, force=false)
    at /home/will/src/polybar/src/polybar/src/components/controller.cpp:481
#6  0x000055555593bef8 in polybar::v3_2_0_60_g6ca4f067::controller::process_eventqueue (this=0x555555bca7f0)
    at /home/will/src/polybar/src/polybar/src/components/controller.cpp:394
#7  0x0000555555947010 in std::__invoke_impl<void, void (polybar::v3_2_0_60_g6ca4f067::controller::*)(), polybar::v3_2_0_60_g6ca4f067::controller*> (
    __f=@0x555555c53480: (void (polybar::v3_2_0_60_g6ca4f067::controller::*)(polybar::v3_2_0_60_g6ca4f067::controller * const)) 0x55555593bb90 <polybar::v3_2_0_60_g6ca4f067::controller::process_eventqueue()>, __t=@0x555555c53478: 0x555555bca7f0)
    at /usr/include/c++/8.2.1/bits/invoke.h:73
#8  0x0000555555942c70 in std::__invoke<void (polybar::v3_2_0_60_g6ca4f067::controller::*)(), polybar::v3_2_0_60_g6ca4f067::controller*> (
    __fn=@0x555555c53480: (void (polybar::v3_2_0_60_g6ca4f067::controller::*)(polybar::v3_2_0_60_g6ca4f067::controller * const)) 0x55555593bb90 <polybar::v3_2_0_60_g6ca4f067::controller::process_eventqueue()>, __args#0=@0x555555c53478: 0x555555bca7f0)
    at /usr/include/c++/8.2.1/bits/invoke.h:95
#9  0x0000555555954f69 in std::thread::_Invoker<std::tuple<void (polybar::v3_2_0_60_g6ca4f067::controller::*)(), polybar::v3_2_0_60_g6ca4f067::controller*> >::_M_invoke<0ul, 1ul> (this=0x555555c53478) at /usr/include/c++/8.2.1/thread:244
#10 0x0000555555954f0f in std::thread::_Invoker<std::tuple<void (polybar::v3_2_0_60_g6ca4f067::controller::*)(), polybar::v3_2_0_60_g6ca4f067::controller*> >::operator() (this=0x555555c53478) at /usr/include/c++/8.2.1/thread:253
#11 0x0000555555954e24 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (polybar::v3_2_0_60_g6ca4f067::controller::*)(), polybar::v3_2_0_60_g6ca4f067::controller*> > >::_M_run (this=0x555555c53470) at /usr/include/c++/8.2.1/thread:196
#12 0x00007ffff69b7063 in std::execute_native_thread_routine (__p=0x555555c53470)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#13 0x00007ffff6740a9d in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007ffff6670b23 in clone () from /usr/lib/libc.so.6
(gdb)
```

Let me know if the core dump would be of any help.

I've yet to be able to reproduce the issue with @kronn's branch so I'll stick with that.
