### ISSUE TITLE
Systray rendering problems

### ISSUE THREAD

**Issue by gilligan** [polybar/polybar#1603]
## Describe the issue

I am using polybar 3.3.0 and I am experiencing issues with the systray display as redrawing doesn't appear to occur correctly. 

**Expected behavior:**

All the icons should be displayed correctly.

**Actual behavior:**

When icons change or new icons appear the new state appears to be drawn on top of the previous one - so it looks as if the change is redrawn on top of the previous state.

**Was it working before?**

I was using 3.2.1 before and there this didn't occur.

## Screenshots

![https://i.imgur.com/OohMqmw.png](https://i.imgur.com/OohMqmw.png)
You can see the nm-aplett looking weird because it is redrawn on top of artifacts from the spinning-dots connection animation.

## Environment:
* WM: i3-gaps 4.16 / compton
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa -curl +i3 -mpd +network(libnl) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: Release
Compiler: gcc-wrapper-7.3.0/bin/g++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: 
```

## Additional context
None.

**Comment by patrick96** [comment]
We've had some similar issues reported even for older versions of polybar (#794, #854, #1143).
We kind of hoped it went away after we merged #595.

We still don't know what's causing it, but we have some suspicions. We would appreciate it if you could answer the following questions to help us gather more information about the issue.

1. Does it happen consistently?
1. Is it always the same icon that gets drawn incorrectly? If so what program is it from?
1. What do you have `tray-background` set to? Does it also happen when you set the tray to be fully opaque?
1. Does it also happen without compton running?

**Comment by patrick96** [comment]
> Attached a screenshot of the corrupt icon, seems like the old icon is not cleared before drawing the new one?

This is likely. But we are still struggling to reliably reproduce this, I have seen this on occasion with the dropbox icon but at seemingly random times. I will try to reproduce it with `nm-applet`
@AkitakiKou What version of polybar are you using?

**Comment by AkitakiKou** [comment]
I installed `polybar 3.3.0-1` from Manjaro's package:

```
$ polybar --version
polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by gilligan** [comment]
@patrick96 could this error message be relevant?

```
error: tray: Failed to put tray above 0x3800002 in the stack (XCB_MATCH (8))
```

**Comment by AkitakiKou** [comment]
I've noticed that the desktop client of Telegram messaging app has this issue as well. The icon randomly get corrupted like this:
![image](https://user-images.githubusercontent.com/17219127/52899384-623eb900-3224-11e9-9b6e-460759ea37b5.png)

The background shouldn't be black, and there are two wierd triangles under the icon itself.

**Comment by behollder** [comment]
I have same issue, but I found if put tray to center bar rendering is clear. right or left tray position got problem.
always clear in my case
![github-screenshot-i3tray-rendering-problem](https://user-images.githubusercontent.com/1114246/55325001-6b11e400-548c-11e9-9332-64fa506358c0.png)

Not clear in right pos
![1323](https://user-images.githubusercontent.com/1114246/55325072-ad3b2580-548c-11e9-9a6b-18491685a665.png)

**Comment by AkitakiKou** [comment]
As this issue is still present on my setup, I searched around about this and found #459 indicating it being a i3 problem rather than polybar itself. Related discussions on i3 [here](https://github.com/i3/i3/issues/1262).

**Comment by Szunti** [comment]
This was fixed in gtk (This is fixed in gtk (https://gitlab.gnome.org/GNOME/gtk/issues/1280) months ago. You should try to get a more recent gtk.

**Comment by tjarvstrand** [comment]
@Szunti 
I'm still experiencing this issue Ubuntu Eoan with gtk 3.24.12. Unless I've misunderstood, this version should contain the fix in the issue you referred to?

**Comment by wmoreland** [comment]
I am also still experiencing this issue with i3 on Arch with gtk 3.24.12 and polybar 3.4.0. In my case it is the Dropbox icon which displays incorrectly. As others have said, if I position the tray in the centre the icon displays correctly but not when it is to the right or left.

**Comment by patrick96** [comment]
We have recently implemented a new tray that runs as a module where we rewrote a lot of the rendering code (#2609, #2689).

Some of these rendering issues may be fixed by this, but there are still some that may occur (I have been struggling to fix the dropbox icon using arbitrary images as its background data).
I am going to close this issue, if you experience rendering issues like these while using the new tray module (the old tray using `tray-position` still has the same issues), please report the application and your polybar version (`polybar -v`) together with a screenshot in #2933.
