### ISSUE TITLE
[Bug]: _NET_DESKTOP_VIEWPORT causes workspace order to change when using multiple monitors (xworkspaces)

### ISSUE THREAD

**Issue by scaramangado** [polybar/polybar#2603]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. `MONITOR=DisplayPort-0 polybar -c polybar_config primary
2. `MONITOR=DisplayPort-1 polybar -c polybar_config secondary
3. Switch workspaces on second screen

### Minimal config

```dosini
[bar/primary]
monitor = DisplayPort-0
override-redirect = true
modules-left = ewmh
enable-ipc = true

[bar/secondary]
monitor = DisplayPort-1
override-redirect = true
modules-left = ewmh
enable-ipc = true

[module/ewmh]
type = internal/xworkspaces
icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-default =
format = <label-state>

label-active = %icon%
label-urgent = %icon%
label-occupied = %icon%
label-empty = %icon%
```

### Expected behavior

Setup: qtile with three workspaces. On launch workspace 1 is displayed on the primary screen, workspace 2 on the secondary screen.

I expect the order of workspaces in my polybar to be constant [1, 2, 3].

### Actual behavior

The order of workspace at launch is [1, 3, 2] and changes depending on which workspaces are visible. (The workspace displayed on the secondary screen is always last.)

### Window Manager and Version

qtile 0.20.0

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.5.7

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### Additional Context / Screenshots

This did not happen with qtile 0.19, the qtile devs believe this comes down to the `_NET_DESKTOP_VIEWPORT` hint being used since the latest version (I opened an issue in their repo, but they directed me here. See qtile/qtile#3375)

If the current behaviour is intended and not a bug, I think there should be at least an option to disable it.

Using `pin-workspaces` is not desirable here, since the bar on my second screen will only show the currently displayed workspace, while the other ones are on my main screen. However any workspace can be displayed on either screen.

**Comment by patrick96** [comment]
Can you provide the output of `xprop -root` as well as the order polybar displays the workspaces and the expected order in at least one situation where things are not behaving as expected.

I'll dig into this more later but I'm just quickly skimming through the code and the individual workspaces are indeed grouped by monitor (more precisely, we use `_NET_DESKTOP_VIEWPORT` to determine which monitors exist). This in itself is not a bug, just how the module behaves, but I'll look at it a little closer later.

**Comment by scaramangado** [comment]
To make things easier I switched to a zero-based numbering.

[Here's the output](https://gist.github.com/scaramangado/e660d1e8c91964322a6d88b55d972b68) of `xprop -root`. It was run on my left screen. Runninf on the right gives `_NET_CURRENT_DESKTOP(CARDINAL) = 1`.

My screens are showing the workspaces 0 (left) and 1 (right). Polybar shows the workspaces in the order: `0 2 1`, I would expect `0 1 2`.

In case it helps I also have a [minimal qtile config](https://gist.github.com/scaramangado/6e6e940866655b603d6785e5c6437beb) that I used to reproduce the issue.

**Comment by patrick96** [comment]
Alright. This is not a bug, just how the module works. It groups workspaces by viewport and then duplicates the entire `format`, once for each monitor.

Not really sure how an option to disable this would look like since the per-monitor grouping is required for `label-monitor` to work.

**Comment by scaramangado** [comment]
I don't really know what `label-monitor` does, but i can imagine simply ignoring the grouping would cause some issues.

I just forked the repo so i can have a `ignore-desktop-viewport` setting for myself and am fine to use polybar like that: scaramangado/polybar@9f9b10f.

I'd be open to submit this as PR, but it's kind of a hacky solution, especially if it breaks other settings. And in the end I don't even know if other people would even face similar issues, as this hasn't come up before.

**Comment by AlexisFinn** [comment]
@scaramangado thank you for the fix. This was driving me crazy.

**Comment by pbrisbin** [comment]
I just updated to a newer version of `xmonad-contrib`, which comes with a new EWMH module that is now setting `_NET_DESKTOP_VIEWPORT` and so I hit this bug. It drives me bananas too. I'm so thankful for at least finding this Issue that fully explains it. I just wanted to mention: I would also very much like to see the `ignore-desktop-viewport` option landed.

**Comment by slotThe** [comment]
We've merged xmonad/xmonad-contrib#791 now, but from a WM perspective it would be great if we didn't have to do this.  @patrick96: Perhaps an `ignore-desktop-viewport` option could be added on the polybar side, much like in @scaramangado's patch?

**Comment by patrick96** [comment]
The main reason why I'm reluctant here is because not grouping the workspaces by monitor makes `label-monitor`, which can show the monitor name of each grouping, completely useless.

But I guess we could produce an error if the config uses `label-monitor`, but grouping by monitor is disabled.
I'll happily accept a PR for this, but I think a better name for the option would be `group-by-monitor` and it defaults to `true`.

**Comment by musjj** [comment]
I'm using a single monitor, but I'm also experiencing this issue. I'm not using polybar, but the built-in bar. The order just goes wack on random, usually after switching workspaces. I still can't figure out the proper reproduction steps.
