### ISSUE TITLE
Tray icons on top of fullscreen windows

### ISSUE THREAD

**Issue by sanjeevkpandit** [polybar/polybar#425]
The system tray icons always stay on top when using the guake terminal. The whole bar hides under guake other than the system tray. Is there any setting where we can hide the system tray icons along with the bar?

![guake](https://cloud.githubusercontent.com/assets/13619272/22828571/21d052ae-efc6-11e6-9763-f200f62cb37d.png)

**Comment by af7567** [comment]
When using polybar with openbox I have the same problem with the systray being on top of everything, even fullscreen programs.  The rest of the bar goes behind fullscreen apps like it is meant to.

**Comment by SuperPrower** [comment]
+1 to this, in OpenBox system tray stays above fullscreen apps, doesn't matter which one - Chrome, Video Player, fullscreen terminal.
My Polybar version is 3.0.5

**Comment by ibrokemypie** [comment]
same thing for full screen games

**Comment by patrick96** [comment]
Can confirm, even happens with `override-redirect = false`

**Comment by ibrokemypie** [comment]
any ideas on the fix for this?

**Comment by patrick96** [comment]
@ibrokemypie To be honest I have no idea how to solve this. The tray currently has a lot of problems, probably because depending on your distro and what other services you have running interfere with it in different ways. At some point the tray is gonna need a major revamp, not sure when this is gonna happen.

**Comment by archmerge** [comment]
I confirm this bug still exist in Polybar 3.1.0 on Arch Linux. Came here to look for a solution. 
ArchMerge with Openbox. When playing vlc and then maximizing the screen the system tray icons are on top of the video playing. Tried changing settings but to no avail.
Anything full screen like firefox will result in having system icons on top of the full screen application.
![polybar system icons](https://user-images.githubusercontent.com/31759042/34931639-079a995c-f9d0-11e7-94c7-27dea7563120.png)

**Comment by Yakoot** [comment]
Archlabs, openbox, polybar 3.1.0, bug still exists

**Comment by tatpap** [comment]
Anyone figure this out yet? I have the same issue?

**Comment by Yakoot** [comment]
It's not a guake problem, tray always on top of all fullscreen applications

**Comment by AlanVerbner** [comment]
@yakoot it only happens with guake to me. I can put Firefox and Chrome in full screen mode without any issues for example...

**Comment by AlanVerbner** [comment]
@Yakoot, that's weird as you can see in the images below, it only shows the icons on top of Guake. I'm using:
- I3wm - 4.13 (2016-11-08)
- Polybar 3.0.5 (I think I compiled it from `4e2e2a7a5e0fe81669031ade0f60e1d379b6516d` commit)

Let me know if there is any other info I could grab from my system.

### Just the desktop, you can see dropbox, slack and clipboard icons
![screenshot from 2018-04-10 07-04-31](https://user-images.githubusercontent.com/3750504/38550745-b6a17376-3c8d-11e8-98dc-832273a84396.png)

### Guake (with the error)
![screenshot from 2018-04-10 07-06-05](https://user-images.githubusercontent.com/3750504/38550761-be809ac2-3c8d-11e8-84c5-519443d51444.png)

### Full screen youtube in Google Chrome 65.0.3325.181
![screenshot from 2018-04-10 07-08-39](https://user-images.githubusercontent.com/3750504/38550878-0cb70046-3c8e-11e8-8189-52f10c356c30.png)

### Full screen page in Google Chrome 65.0.3325.181
![screenshot from 2018-04-10 07-09-45](https://user-images.githubusercontent.com/3750504/38550920-2d1d84cc-3c8e-11e8-9312-c8a5b909bc0d.png)

**Comment by patrick96** [comment]
Alright, from testing this I have figured out the following things:
It happens in i3, openbox but not in herbstluftwm.
In openbox it seems to happen all the time, in i3 only with guake (and maybe some others).

I suspect the problem is that polybar cannot configure the tray to be directly above polybar in those two WMs. I have opened PR #1203 to print an error when this happens. I'm going to try to figure out why this doesn't work in those two WMs

**Comment by varakh** [comment]
I am getting this too. I am on arch and openbox.

![screenshot-2018-05-06-123250](https://user-images.githubusercontent.com/4570674/39672395-d16c5e40-5129-11e8-8eb3-295987f425de.png)

**Comment by coderobe** [comment]
I can reproduce this with xfwm as well.

**Comment by Jackojc** [comment]
Similar issues with XFWM4

**Comment by tgharib** [comment]
I had this problem in Dota 2. I fixed it by first putting the game in full screen mode. Then, I toggled i3's full-screen by hitting mod+f.

**Comment by 132ikl** [comment]
Can this issue be renamed for clarity?

**Comment by douglasrizzo** [comment]
I'm on Manjaro Linux 18.0.0 with polybar 3.2.1 and i3 window manager.

I confirm this happening when playing Stellaris on fullscreen. The tray initially disappears when the game goes fullscreen, but once I change workspaces and come back to the game, the tray stays on top of the game forever.

This doesn't happen for me with other fullscreen applications, such as Visual Studio Code, Firefox or Terminator, for example.

**Comment by LukyIsHere** [comment]
On bspwm, ArchLabs, the tray overlays fullscreen apps such as Firefox and YouTube fullscreen.

**Comment by patrick96** [comment]
Hit a small speedbump, my fix messes up the tray positioning when using offsets. My exams are starting now, so it will probably be a few weeks until I can get to this.

**Comment by setevoy2** [comment]
Well actually after a couple of weeks I found this bug as some nice feature :-)
Indeed - now I can watch movie etc in fullscreen and still will be able my tray with Slack/Skype/Viber icons and will see if there are new messages without needed to enable annoying pop-up notifications.
Arch/Openbox.

**Comment by patrick96** [comment]
@setevoy2 It's not a bug, it's a feature :wink:
The way I implemented the fix, you should still be able to reenable the buggy functionality once it's merged.

**Comment by powerriegel** [comment]
Same problem for VirtualBox. Polybar on the host machine appears over guest machines in fullscreen mode. Quite distractive. If I work in a VM in full screen mode, I don't want to see anything from host machine.

**Comment by RustemB** [comment]
oh, bspwm, archlinux, same polybar problem :(

**Comment by Jens0512** [comment]
Openbox, same problem.

```
$ polybar --version
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by olealgoritme** [comment]
i3-gaps v 4.16.1, same problem.
```
❯ i3 --version
i3 version 4.16.1-184-g00181678 (2019-07-03, branch "shape")

```

```
❯ polybar -vvv
polybar 3.4.0-37-g8d3dedc

Features: +alsa +curl +i3 +mpd +network(wireless-tools) +pulseaudio +xkeyboard
```

**Comment by autoferrit** [comment]
Same on arch i3 distro.
```bash
$ polybar --version
polybar 3.4.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```bash
$ uname -a
Linux ferritprime 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64 GNU/Linux
```

**Comment by JoshuaJChan** [comment]
Problem persists on Openbox using Arch
`
polybar --version
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
`

**Comment by JDuchniewicz** [comment]
Problem still persists, Openbox + Arch
`
polybar --version
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
`

**Comment by im-n1** [comment]
This issue is ~3 years old. Guys seriously....c'mon.

**Comment by 132ikl** [comment]
@im-n1 If you are interested in seeing this fixed, you can contribute to the project.

**Comment by im-n1** [comment]
I'm not a C++ developer but thanks for the offer.

**Comment by JDuchniewicz** [comment]
Do you know what is required in order to fix that? I could lend a hand, but I am totally unfamiliar with this project yet.

**Comment by 132ikl** [comment]
@JDuchniewicz @patrick96 could probably help get you started, and you can see the PR here: https://github.com/polybar/polybar/pull/1615.

**Comment by Jens0512** [comment]
:smile:

**Comment by ForumPlayer** [comment]
Hey guys, nothing yet?
The same bug, but on Openbox (Debian 10)

**Comment by setevoy2** [comment]
> Hey guys, nothing yet?
> The same bug, but on Openbox (Debian 10)

#notabug #feature
:-)
Indeed - this is a good "bug" and it's useful when you're in fullscreen mode but still have access to volume control, notifications tray, etc.

**Comment by 132ikl** [comment]
@setevoy2 oh great, you're one of those spacebar-overheaters

**Comment by jakeogh** [comment]
On bspwm 0.9.9 and polybar polybar 3.4.3 adding `wm-restack = bspwm` to ~/.config/polybar/config made it so that fullscreen windows (like mpv) are above (over) the polybar.

**Comment by yuukiasuna00** [comment]
> On bspwm 0.9.9 and polybar 3.4.3 adding `wm-restack = bspwm` to ~/.config/polybar/config made it so that fullscreen windows (like mpv) are above (over) the polybar.

Thank you

**Comment by ngmoviedo** [comment]
On i3-gaps I have never observed the tray over fullscreen windows, but it does stay on top of floating windows and even i3lock sometimes, if it happens to launch before Polybar. I'm using `wm-restack = i3` and `override-redirect = false`.
The issue is technically solved if the latter is set to true, but then windows draw over Polybar. This again can be solved increasing the top gap on i3, but this solution is not without flaw, as it does not go well with the smart_gaps function (Polybar gets totally covered when there's only one window on screen).

**Comment by dwsong07** [comment]
I have a idea to solve this temporarily.
If a fullscreen is enabled, then hide the bars by "polybar-msg". And if a fullscreen is disabled, then show them back.
The problem is how to check if a fullscreen is enabled.

Sorry for my bad english :)

**Comment by mg979** [comment]
It happens in fluxbox too.

**Comment by treditre** [comment]
The following is not a solution but a workaround:

1) Enable the inter-process messaging by defining the bar parameter:
`enable-ipc = true`
inside **~.config/polybar/config** under the bar parameters [bar/your_bar_name]

2) Open a text editor (nano, gedit, atom, etc) and create a new text file with a . sh extension (i.e. check.sh):

```
#!/bin/bash

#Get screen size
root_geo=$(xwininfo -root | awk -F'[ +]' '$3 ~ /-geometry/ {print $4}')

#infinite loop
while :
do
  #Check if any window fills the screen
  win_fills=$(xwininfo -root -tree | grep $root_geo)
  #If any window fills the screen hide polybar, otherwise show it
  if [ -z "$win_fills" ]
    then
      polybar-msg cmd show
  else
      polybar-msg cmd hide
  fi
  sleep 1
done
```

And save it wherever you want (i.e. ~.config/polybar/check.sh).

3) Make it executable:
`chmod +x ~.config/polybar/check.sh`

4) Now add this file to your autostart apps. For instance, in openbox open ~.config/openbox/autostart and add:
`sh ~/.config/polybar/check.sh &`
below the command to start polybar.
Reboot (or restart openbox) and that´s it!

**Comment by pciavald** [comment]
in LXDE (openbox) i see the error in the log output:
```
error: tray: Failed to put tray above 0x0a00002 in the stack (XCB_MATCH (8))
```

**Comment by korewaChino** [comment]
This issue is still a thing in Xfwm4. 
```
> $ polybar --version                                                          
polybar 3.5.6

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by A-Siam** [comment]
@treditre your _workaround_ worked for me as well, I just wanted to add a few side effects that happened to me in **awesome wm** 

1- If you don't specify `override-redirect = true` your bar will have a weird behaviour after you show it again similar to https://github.com/polybar/polybar/issues/1484 so make sure to add it to your bar

2- if you did step 1 in awesome wm you will notice that the whole bar is overriding the windows, that is expected. You can fix it in your rc.lua as following
```lua
-- add top padding
awful.screen.connect_for_each_screen(function(s)
    -- 32 is my bar height change it to whatever you like.
    awful.screen.padding(s, {top = 32})
end)

```

**Comment by snxraven** [comment]
Its not a full fix, but I was able to remove this behavior by replacing the compositor with Compiz 0.9

**Comment by mg979** [comment]
I found a solution that works for me in fluxbox:

- no polybar tray
- set some right padding to make room for tray
- load a tint2 panel that only holds the tray and position it
- set tint2 background color to match polybar

I also set windows layers so that tint2 stays above polybar, but that's WM dependent, in fluxbox is (`.fluxbox/apps`)
```
[app] (name=tint2) (class=Tint2)
  [Layer]	{2}
[end]
[app] (class=Polybar)
  [Layer]	{8}
[end]
```

![polybar](https://user-images.githubusercontent.com/26169924/135736470-a61bf244-1b22-4c95-b6a5-ee77b58895f7.png)

**Comment by Alone-Wolf13785** [comment]
i just did as this dude said and set some right padding in i3gaps & polybar and works correctly
thanx dude <3

**Comment by InvisibleRasta** [comment]
has anyone been able to fix this for openbox?

**Comment by julmajustus** [comment]
Still occuring in openbox + arch & polybar 3.61. Combining polybar with tint2 tray is only workable solution that I've found.

**Comment by s3rj1k** [comment]
Same here with WM: Metacity, polybar 3.6.3.

Is there a hacky patch for polybar to fix this until we get proper tray support in 3.7.0?

**Comment by Lamborge** [comment]
5 years guys

**Comment by DonCammne** [comment]
Same problem with Archlinux and AwesomeWM.

**Comment by jazzmess** [comment]
Still happening in current version of Archcraft.

**Comment by Alanon202** [comment]
I work around this with an (extremely) hacky solution, might be useful for some.

First, I installed stalonetray and set it up so that it’s basically invisible (I think I put it under Polybar or descreased the size). I then created a  clickable separator element between the Polybar tray and the rest of the bar. 

Clicking the separator invokes a simple script that starts or kills stalonetray. In effect, whenever stalonetray is started, it takes away control from Polybar tray, and as soon as stalonetray is killed, Polybar tray is back in an instant.

I find this much more stable than forcing Polybar to restart or change internal stacking settings, at least for using it with Openbox. This allows for manual control, which is all I really need.

**Comment by patrick96** [comment]
This is finally fixed by #2609 if you are using the new tray module :rocket:

**Comment by dreamkinn** [comment]
Hi, I am still experiencing this issue on archcraft openbox and polybar 3.6.3 :
```
~ polybar --version
polybar 3.6.3
Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard
```

**Comment by patrick96** [comment]
This is going to be in 3.7

**Comment by LuckyToaster** [comment]
I am experiencing the same problem with the tray being on top of maximized windows in openbox
