### ISSUE TITLE
System tray sometimes overlapping the rest of the bar  

### ISSUE THREAD

**Issue by seysn** [polybar/polybar#591]
I've seen some weird issues with the systray, since it's overlapping with the rest of the bar on some conditions. 
First it started to overlap when my download module had less than 3 digits, so i replaced the line
`label-connected = %downspeed%` to `label-connected = %downspeed:8%` which add space so it's like the module always have the same width even with 1 digit.

But then it started to overlap depending the number of icon the systray have. Here's some examples with 2 and 3 icons :
![polybar-nok](https://cloud.githubusercontent.com/assets/6440133/26275181/5ad7658c-3d5b-11e7-8743-b89d29e48fd6.png)
![polybar-ok](https://cloud.githubusercontent.com/assets/6440133/26275225/3dcf5782-3d5c-11e7-92d0-90bc5197d58e.png)

I saw some similar issues about systray overlap like #425 but i don't know if the problem come from the same thing.
Also here's my [polybar config](https://gist.github.com/seysn/fa6d1b7478a48cf317e40b784f3f0d62)

**Comment by Plasticoo** [comment]
This sometimes happens to me too! When I get 3 icons, if the first one disappears (because I closed the program), then it will be shown a blank space, overlapping the rest of the bar.

**Comment by 5haffl** [comment]
This issue affects me too. It is not easy to track down the cause, since it happens "randomly".
![overlap](https://user-images.githubusercontent.com/6308274/29063340-a37d64e0-7c25-11e7-84ed-45cc4e5dfb75.png)

**Comment by patrick96** [comment]
I started noticing the same thing too. For me it only seems to happen with the dropbox icon.
![2017-09-07-003457_92x29_scrot](https://user-images.githubusercontent.com/2452038/30137615-6f972264-9364-11e7-8587-bda9759446d1.png)
(Note: The overlap is only very small)

**Comment by SeerUK** [comment]
Not sure if this is related, but if I close something, the space isn't reclaimed - as if the tray area doesn't resize completely properly when something disappears. Right now I end up reloading polybar:

![](https://i.imgur.com/2TZfQ0o.png)
![](https://i.imgur.com/jVczhHg.png)

My power icon ends up obscured.

**Comment by surrsurus** [comment]
Happens to me too, tray on right side overlaps the bar... does it happen when the tray is on the left?
![bar wyd](https://user-images.githubusercontent.com/9388076/30838649-cff7bd00-a23a-11e7-8712-2a577b2f71a2.png)

**Comment by alexozer** [comment]
This happens to me sometimes when the bar first starts on first login, but rarely (if ever) happens when I restart the bar.

**Comment by anhtuann** [comment]
I think @SeerUK is into something. It happens a lot when I eject an USB key and the fuse icon disappears.

**Comment by yellowgh0st** [comment]
I encounter this too.

**Comment by HaoZeke** [comment]
I can confirm this as well.. It appears to be because the tray is first drawn, then the systray icons appear.. 
![polybug1](https://user-images.githubusercontent.com/4336207/37398659-3bb18a22-27a5-11e8-9193-d7164e752fa1.png)

For me the situation is worse, as on my smaller screen the icons are basically drawn all over the place.

![polyBug2](https://user-images.githubusercontent.com/4336207/37398696-5045296c-27a5-11e8-8236-5964dc0aab1e.png)

**Comment by jaagr** [comment]
If you are able to compile the project from source, please try out the `fix/reconfigure-tray` branch to see if it changes the behavior.

**Comment by jaagr** [comment]
I did notice now, when trying to reproduce the issue, that whenever the right* side of the bar occupies more space than possible, it will start truncating the modules within it; fading them out with a gradient. This is by design since, currently, the tray area is not considered being part of the bar.

_* if the tray is configured to appear on the right_

**Comment by jfrankenau** [comment]
@jaagr, I've tested the `fix/reconfigure-tray` branch against the issues described in #944 and it seems to work fine.

**Comment by lebarondemerde** [comment]
The fix appear to work for me too.

Thanks!

**Comment by lebarondemerde** [comment]
Not really fixed. The bug does not happen over the date module anymore but it appear over the mpd module in some circumstances.

In my setup the tray just overlap the mpd module when the music is playing (toggle).

Paused: no overlap.
![tray_good](https://user-images.githubusercontent.com/20615335/37867631-53796134-2f93-11e8-9548-3d587bc7dbf7.png)

Playing: overlap.
![tray_bad](https://user-images.githubusercontent.com/20615335/37867639-6a5609de-2f93-11e8-87d6-5e62e49108b7.png)

Just in case, the config is fine. Disabling the tray and everything works as expected.

Thanks!

**Comment by NBonaparte** [comment]
@jaagr is 0edaead ready to be merged?

**Comment by nicklan** [comment]
I'm running the `fix/reconfigure-tray` branch, and the behavior is a little better, but still not fixed.  Even restarting the bar often doesn't fix things.

Let me know if there's more debug info that could help out.

**Comment by nicklan** [comment]
A bit of extra info: For me, and easy way to trigger the problem is using Qt based systray icons.  If I run [this systray example app](https://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html), polybar never shifts over its contents for the newly created icon.

Maybe there is something strange/broken about how Qt reserves space in the tray?

**Comment by Spheerys** [comment]
I have the problem too...

**Comment by Spheerys** [comment]
I have the problem too... and I also thinking the problem comes from QT icons.
I made a test without open qt application and I did have the issue in those circumtances...

**Comment by CadaverLab** [comment]
Just for the sake of completion, i'd like to point out this also happens when your tray is on the left side of the bar as well

**Comment by rudevdr** [comment]
I use [indicator-kdeconnect](https://github.com/Bajoja/indicator-kdeconnect
) and when a device is disconnected, the notification tray overlap and the icon hides and when device is reconnected the tray becomes invisible/icon doesn't show up again.

**Comment by guiemi** [comment]
I'm facing the same problem. Tray icons poorly displayed, and overlapping Polybar icons.

![2018-07-22-225337_1365x44_scrot](https://user-images.githubusercontent.com/24235344/43053259-1fb6ee66-8e02-11e8-8279-eceb1cb5fe28.png)

**Comment by Spheerys** [comment]
I have Polybar 3.2.1 and I still have the issue with qt icons :(

**Comment by wmoreland** [comment]
I'm also using Polybar 3.2.1 and experiencing the issue. Not sure whether Qt icons are involved or not though... How could I find that out? My system tray usually contains the network manager applet and Dropbox, and then I've been using [tomate-gtk](https://github.com/eliostvs/tomate-gtk) to reproduce the polybar-tray issue alongside a minimal config file (below). In the meantime I've just been using padding to ignore the issue but it isn't ideal.

<details>
[bar/example]

modules-left = i3
modules-right = date
tray-position = right
;Use padding-right=5 to compensate for 1 missing tray icon's worth of space
;padding-right=5

[module/i3]
type 	= internal/i3

[module/date]
type 	= internal/date
date = 
date-alt = %Y-%m-%d
time 	= "%H:%M"
time-alt = %H:%M:%S
label = %date% %time%
</details>

**Comment by ivanbartsov** [comment]
My two cents: Polybar 3.2.1, I can reliably reproduce the overlap/blanking issue by adding and removing an icon from tray.
Example (_tray painted red for visibility_)
* reload for fresh state: `pkill -USR1 polybar`
![2018-11-12-22 01 35-037067242](https://user-images.githubusercontent.com/1104527/48355705-382aa780-e6c7-11e8-95c1-06ec6df1b07e.png)
* copy something to trigger the file operation tray icon
![2018-11-12-22 02 00-319509023](https://user-images.githubusercontent.com/1104527/48355746-5395b280-e6c7-11e8-87ef-6b2a6d27ea9b.png)
* cancel the op: the icon is gone, the empty space in tray is still there, but the main polybar panel seems to think it's not - it's partly overlapped by the blank tray space
![2018-11-12-22 02 10-602631410](https://user-images.githubusercontent.com/1104527/48355848-8770d800-e6c7-11e8-82ee-9fc7e0a83110.png)

**Comment by patrick96** [comment]
@ivanbartsov where is that file operation icon from?

**Comment by ivanbartsov** [comment]
@patrick96 it's Thunar's file copy routine. I believe it also shows the same thing for deletion. I just did a Ctrl-c Ctrl-v on a big video file to get it. Running Transmission-gtk and closing it has the same effect.

**Comment by patrick96** [comment]
I wasn't able to reproduce it, neither with thunar nor with transmission-gtk

**Comment by ivanbartsov** [comment]
@patrick96
As I said, I'm using release 3.2.1 (latest in Arch AUR). Any chance you're using latest repo head to reproduce?

I will try when I have a moment to pull and compile and check back - I suspect there are a lot of commits that might have fixed it in the dev version which haven't got into the release yet, e.g. [this one](https://github.com/jaagr/polybar/commit/35aca5b3683b6c025fe769dfc9ecec6fbc347fa0)
Also other people reporting here might also just be using the release version.

**Comment by patrick96** [comment]
So I guess I'm closing this. 

If anyone still has this issue and is using any version newer than `3.2.1` (or compiled against `master`), please report here.

**Comment by Spheerys** [comment]
I'm also an Archer and I have insatlled the last version of polybar 3.2.1-1
But after a restart I still have the issue.
I'm using keepassxc, which is a qt application, in case this information could be useful.

**Comment by patrick96** [comment]
@Spheerys Can you try `polybar-git`, it should be fixed there.

**Comment by inorichi** [comment]
I can still see this issue (with latest master, I compiled directly from git with a small patch I made to add window icons to workspaces) but it only happens if I have KeePass open. Sometimes the KeePass icon is even anchored to the left (above the `I` workspace), but when I close that app, the tray recovers itself properly.

When I only have telegram:
![image](https://user-images.githubusercontent.com/3521738/48946380-da4f5880-ef2d-11e8-92bd-2e30bb2d0049.png)

When I open KeePass, its icon isn't shown in the tray and everything remains the same as the screenshot above.

When I open another app that has a tray icon, like skype:
![image](https://user-images.githubusercontent.com/3521738/48946479-2c907980-ef2e-11e8-8e34-ae8518458069.png)

But if I close Keepass, the tray is fine again:
![image](https://user-images.githubusercontent.com/3521738/48946569-71b4ab80-ef2e-11e8-82d5-5d4393583782.png)


I guess this has to do with how KeePass handles the tray icon, I don't know if this is something that can be fixed in polybar...

**Comment by patrick96** [comment]
@inorichi What is the small patch to add icons to the workspaces?

keepass on linux uses mono and we've had issues with mono icons before (see #545). I don't think this can be directly solved within polybar.

**Comment by patrick96** [comment]
Alright, so most definitely this was a mono issue.

**Comment by Spheerys** [comment]
> Edit: as mentioned in the linked Keepass issue, using keepass2-plugin-tray-icon from the AUR fixes it. 

I have insatlled this package but nothing change with my tray :(

**Comment by patrick96** [comment]
@Spheerys Do you have polybar 3.3.0 installed?

**Comment by nemanjan00** [comment]
It just seams to be completly rantom. 
I reset it and randomly it just works and sometimes it just does not. 

It sounds to me like a race condition of at which point icons register to tray or something like that (not familiar with implementation of tray)

**Comment by patrick96** [comment]
Yeah, for some reason polybar doesn't properly handle some new icons. Which icons are overlapping? We had issues with, I think, qt icons.

**Comment by Spheerys** [comment]
I still have the issue too.
I switch from KeepassXC to "Keepass Password Safe", and the issue is still there.
Probably because it's also qt application/icon...

**Comment by EmilyBjoerk** [comment]
I'm not sure where it was supposed to be fixed but I can confirm it still happens on 3.2.1 in gentoo repository (latest available stable). I have worked around it by having all modules in left/center and tray in right so there is nothing to overlap.

**Comment by patrick96** [comment]
@EmilyBjoerk This is only fixed in 3.3.0, so it's expected that you still see it.

**Comment by Xananax** [comment]
Still happening for me with 3.3.0, on Arch 
![image](https://user-images.githubusercontent.com/836082/51790071-633a7880-2199-11e9-9f84-ee7376b306a2.png)

Workaround:

```
 [module/spacer]
 type = custom/text
 content-background = ${colors.background}
 content-foreground = ${colors.background}
 content-padding = 4
 content =                |
```

I then add `spacer` to my list of modules.

However, after that I got a garbled systray:

 
![image](https://user-images.githubusercontent.com/836082/51790202-aa753900-219a-11e9-9fcb-1eabfc2d5a10.png)

But this was happening with i3blocks too, so I don't think it's polybar related. It might be related to the overlapping though.

**Comment by patrick96** [comment]
Well, I guess I'm reopening this :frowning_face:

**Comment by Yves1024** [comment]
@patrick96 @Xananax happening for me too. :frowning_face: 3.3.0 on Arch
![image](https://user-images.githubusercontent.com/35786611/52165958-53470980-2742-11e9-84ad-7996f2050a74.png)
![image](https://user-images.githubusercontent.com/35786611/52165970-825d7b00-2742-11e9-9345-87443dba9fb7.png)

**Comment by Yves1024** [comment]
restarting X,then it works.Have you tried to reboot? @patrick96 @Xananax 
![image](https://user-images.githubusercontent.com/35786611/52166153-75da2200-2744-11e9-8369-a8586198b30e.png)

**Comment by EmilyBjoerk** [comment]
Not sure if related but I had my system tray render on top of a full screen window (game) yesterday...

**Comment by patrick96** [comment]
@EmilyBjoerk this is a different issue (see #425)

@Yves1024 Restarting polybar often works but the issue never really goes away.

**Comment by porkloin** [comment]
Also experiencing this issue.

One thing worth noting, however, is that I never encountered this issue on my old machines (720p internal display on my laptop, 1440p dual monitors on desktop). I just got a new laptop with a 4k screen and now I'm experiencing this issue for the first time. Curious how many other folks are on very high resolution screens. I had to crank up the `tray-maxsize` a lot for icon visibility, so I wonder if they're rendering past their bounds due to that higher maxsize value.

**Comment by alexozer** [comment]
I'm on a MacBook Pro retina screen, so I also wonder if that high
resolution matters.

**Comment by Xananax** [comment]
Yep, I'm on 4K

**Comment by evanc577** [comment]
Setting `fixed-center = false` fixes the issue for me. I have no center-aligned modules, so I think polybar is trying to force all left/right aligned modules to only half the bar even when there are no centered modules.

**Comment by porkloin** [comment]
@evanc577's suggestion of `fixed-center = false` worked for me. Can't say for others, but my tray is behaving as expected now :smile:

**Comment by Spheerys** [comment]
Huhu... I want to try but polybar won't restart with this parameter...

**Comment by andrewnicolalde** [comment]
Also having this issue, also using a 4k display.

**Comment by jdamp** [comment]
I can also confirm that @evanc577's solution fixes the issue for me.

**Comment by andrewnicolalde** [comment]
> I can also confirm that @evanc577's solution fixes the issue for me.

Are you on a high DPI display?

**Comment by Spheerys** [comment]
I'm using a DPI screen and the @evanc577 solution doesn't work for me.

**Comment by alexozer** [comment]
@evanc577 's solution seem to work temporarily, but just now I logged in and the issue reappeared:
![overlap](https://i.imgur.com/7vvqGwS.png)

**Comment by fuzunspm** [comment]
i'm having the same issue plus my tray icons sometimes goes to secondary monitor but it should never appear except primary according to the config file

**Comment by 0xANDREW** [comment]
just installed from master (7724c4dccb18ed9e48b050713540a2d05eacd2a1), same issue.

![Screenshot from 2019-05-25 10-29-30](https://user-images.githubusercontent.com/365047/58372822-288ee580-7ed8-11e9-99ff-6c417e19bc66.png)

adding `label-margin = 3` to `[module/date]` fixed it for me, but it's ugly. i should note that anything less than 3 still gets overlapped by the tray.

**Comment by patrick96** [comment]
I think I found the problem. Could you please go over to #1936 and see if that fixes your issue.

I have determined that this occurs when you have `fixed-center = true` (or not set at all) and the right modules take up a lot of space. Can you confirm?

**Comment by matejdro** [comment]
I'm experiencing this issue on 3.5.2, with `fixed-center = false`

**Comment by patrick96** [comment]
@matejdro Please open a new issue. The issue is likely unrelated, especially since this only happened with `fixed-center = true`.

**Comment by Anderson0xFF** [comment]
I'm experiencing this issue on 3.6.3
